# Generated by Django 5.2.8 on 2025-12-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField()),
                ('eventDate', models.DateField(blank=True, null=True)),
                ('eventTime', models.TimeField()),
                ('eventDay', models.CharField(choices=[('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT'), ('SUN', 'SUN')], default='SUN')),
                ('location', models.TextField()),
                ('isReoccuring', models.BooleanField(default=False)),
                ('churchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
                ('ministryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministries.ministries')),
            ],
            options={
                'ordering': ('eventName',),
            },
        ),
    ]
