# Generated by Django 4.2.16 on 2026-03-27 02:34

from django.db import migrations, models
import django.db.models.deletion
import faces.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0005_remove_person_faceencoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.FileField(upload_to=faces.models.upload_to)),
                ('pics2', models.FileField(blank=True, null=True, upload_to=faces.models.upload_to)),
                ('pics3', models.FileField(blank=True, null=True, upload_to=faces.models.upload_to)),
                ('encoding', models.JSONField(default=dict)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
