# Generated by Django 4.2.16 on 2026-01-13 13:47

from django.db import migrations, models
import faces.models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faces',
            name='pics2',
            field=models.FileField(blank=True, upload_to=faces.models.upload_to),
        ),
        migrations.AddField(
            model_name='faces',
            name='pics3',
            field=models.FileField(blank=True, upload_to=faces.models.upload_to),
        ),
    ]
