# Generated by Django 4.2.16 on 2026-03-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faces',
            name='pics2',
        ),
        migrations.RemoveField(
            model_name='faces',
            name='pics3',
        ),
    ]
