# Generated by Django 4.2.16 on 2026-01-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_faces_pics2_faces_pics3'),
    ]

    operations = [
        migrations.AddField(
            model_name='faces',
            name='faceEncoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
