# Generated by Django 4.2.16 on 2026-04-13 11:49

from django.db import migrations
import encrypted_json_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_remove_faces_pics2_remove_faces_pics3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='encoding',
            field=encrypted_json_fields.fields.EncryptedJSONField(crypter=None, default=dict),
        ),
    ]
