# Generated by Django 6.0.5 on 2026-05-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_alter_faces_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='pics',
            field=models.CharField(blank=True, default='welcome', max_length=500, null=True),
        ),
    ]
