# Generated by Django 4.2.16 on 2026-03-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_faces_faceencoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faces',
            name='faceEncoding',
        ),
    ]
