# Generated by Django 6.0.5 on 2026-05-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0004_alter_faces_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='pics',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
