# Generated by Django 6.0.5 on 2026-05-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0005_alter_faces_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='pics',
            field=models.CharField(default='welcome', max_length=500),
        ),
    ]
