# Generated by Django 5.2.8 on 2025-12-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('churchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
