# Generated by Django 4.2.16 on 2026-01-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.EmailField(max_length=254),
        ),
    ]
