# Generated by Django 4.2.16 on 2026-01-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.TextField(),
        ),
    ]
