# Generated by Django 5.2.8 on 2025-12-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capturemethod', '0001_initial'),
        ('person', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInTimestamp', models.DateTimeField()),
                ('checkOutTimestamp', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('captureMethodId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capturemethod.capturemethod')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('servicesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
            options={
                'ordering': ('comment',),
            },
        ),
    ]
