# Generated by Django 4.2.16 on 2025-12-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkInTimestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
