# Generated by Django 4.2.16 on 2026-01-14 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_checkintimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendanceDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('personId', 'attendanceDate'), name='unique_person_date_attendance'),
        ),
    ]
