# Generated by Django 4.2.16 on 2026-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_attendancedate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('comment', 'attendanceDate')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendanceDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
