# Generated by Django 4.2.16 on 2026-03-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_person_date_attendance',
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('personId', 'attendanceDate', 'servicesId'), name='unique_person_date_attendance'),
        ),
    ]
