# Generated by Django 6.0.5 on 2026-05-14 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0006_alter_person_churchid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='visitor followup', max_length=255)),
                ('dueDate', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', unique=True)),
                ('comment', models.CharField(max_length=500)),
                ('followeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('followerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'dueDate'),
            },
        ),
    ]
