# Generated by Django 5.2.8 on 2025-12-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.TextField()),
                ('dueDate', models.DateField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('followeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee_set', to='person.person')),
                ('followerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower_set', to='person.person')),
            ],
            options={
                'ordering': ('isCompleted', 'dueDate'),
            },
        ),
    ]
