import os
# Force Matplotlib to use a tiny, non-interactive backend
os.environ['MPLBACKEND'] = 'Agg'
# Point the config to /tmp so it doesn't try to build a persistent cache
os.environ['MPLCONFIGDIR'] = '/tmp/matplotlib_cfg'


"""
Django settings for apis project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY','')
EJF_ENCRYPTION_KEYS = [
    os.environ.get('EJF_ENCRYPTION_KEYS'),
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django_extensions',  # Optional - not needed for HTTPS server
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'rest_framework_simplejwt.token_blacklist',
    'dbbackup',
    'auditlog',
    'church',
    'household',
    'role',
    'membership',
    'permissions',
    'capturemethod',
    'ministries',
    'services',
    'person',
    'contact',
    'leadership',
    'attendance',
    'faces',
    'user',
    'auth',
    'analytics',
    'report',
    'message',
    'followup',
    'encrypted_json_fields',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'anymail',
]

MIDDLEWARE = [
    'user.TraceMemoryLeakMiddleWare.SystemMonitorMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'apis.urls'

AUDITLOG_LOGENTRY_MODEL = 'auditlog.LogEntry'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apis.wsgi.application'


# Face Recognition Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 3600,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Set Anymail as your email backend
EMAIL_BACKEND = "anymail.backends.mailtrap.EmailBackend"

ANYMAIL = {
    # Found in Mailtrap Settings -> API Tokens
    "MAILTRAP_API_TOKEN":os.environ.get("MAILTRAP_API_TOKEN") ,
    
    # OPTIONAL: Only set this if you want to use the Sandbox for testing.
    # If omitted, Anymail uses the Transactional Email API/SMTP service.
    "MAILTRAP_SANDBOX_ID": os.environ.get("MAILTRAP_SANDBOX_ID"),
}

# Standard Django email settings
DEFAULT_FROM_EMAIL =  os.environ.get('DEFAULT_FROM_EMAIL','')
SERVER_EMAIL =  os.environ.get('DEFAULT_FROM_EMAIL','')

# Site Configuration for Email Links in production
SITE_NAME = 'Church Membership and Attendance Management System'


# TWILIO SMS CONFIGURATION
# Get your credentials from https://www.twilio.com/console
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')  # Your Account SID
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')    # Your Auth Token
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '') # Your Twilio Phone Number (e.g., +1234567890)

#custom user
AUTH_USER_MODEL = 'user.User'

#rest framework settings

SPECTACULAR_SETTINGS = {
    # Add this line to allow user access the Docs by logining into /admin/ 
    'SERVE_AUTHENTICATION': [
        'rest_framework.authentication.SessionAuthentication', 
    ],
    'TITLE': 'Church Attendance and Membership Management API',
    'DESCRIPTION': 'Church attendance and membership and management system helps church track attendance and membership using AI Face Recognition',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # 1. Shows the "Authorize" button so devs can test live
    'SECURITY': [{'jwtAuth': []}],
    'APPEND_COMPONENTS': {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },

    # 2. Recommended: Keep the docs private to the team
    # This prevents random internet users from seeing your API structure
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAuthenticated'],
}


REST_FRAMEWORK = {
'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
'PAGE_SIZE':10,
'MAX_PAGE_SIZE':10,
'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user':'1000/day',
        'refresh': '25/hour',
        'face_login': '100/day',
        'password_login': '100/day',
        'otp_login': '100/day',
        'password_reset_request':'100/day',
        'otp_verification':'100/day',
        'password_reset':'100/day',


    },
'DEFAULT_FILTER_BACKENDS': (
'django_filters.rest_framework.DjangoFilterBackend',
'rest_framework.filters.OrderingFilter',
'rest_framework.filters.SearchFilter',
),
'DEFAULT_AUTHENTICATION_CLASSES': (
'rest_framework_simplejwt.authentication.JWTAuthentication',
),
'DEFAULT_PERMISSION_CLASSES': (
            'rest_framework.permissions.IsAuthenticated', # Or other default permissions
),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
    'UPDATE_LAST_LOGIN': True,
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Actual directory user backups files go to
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#used on production with whitenoise
DBBACKUP_FILENAME_TEMPLATE = 'backup_db_{datetime}.sql'
DBBACKUP_MEDIA_FILENAME_TEMPLATE = 'backup_file_{datetime}.tar'

# different password hashers for better security(argon2 most secured and fastest, bcrypt is also secured and faster than default, pbkdf2 and pbkdf2sha1 are the default hashers and less secure and fast)
#to use any of the hashers make it come first in the list
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]
