"""
Django settings for apis project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY','')
EJF_ENCRYPTION_KEYS = [
    os.environ.get('EJF_ENCRYPTION_KEYS'),
]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = []

# Get the Render URL (e.g., ://onrender.com)
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '*')

if RENDER_EXTERNAL_HOSTNAME:
    # This adds the Render URL to allowed hosts
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    
    # Required for Django 4.0+ to prevent "CSRF verification failed"
    CSRF_TRUSTED_ORIGINS = [f'https://{RENDER_EXTERNAL_HOSTNAME}']
else:
    # Fallback for local development
    ALLOWED_HOSTS = ['192.168.1.5', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django_extensions',  # Optional - not needed for HTTPS server
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'rest_framework_simplejwt.token_blacklist',
    'dbbackup',
    'auditlog',
    'church',
    'household',
    'role',
    'membership',
    'permissions',
    'capturemethod',
    'ministries',
    'services',
    'person',
    'contact',
    'leadership',
    'attendance',
    'faces',
    'user',
    'auth',
    'analytics',
    'report',
    'message',
    'encrypted_json_fields',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'user.TraceMemoryLeakMiddleWare.SystemMonitorMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

if not DEBUG:  # Only apply these in production
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


ROOT_URLCONF = 'apis.urls'

AUDITLOG_LOGENTRY_MODEL = 'auditlog.LogEntry'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apis.wsgi.application'


# Database Local PostgreSQL
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('ENGINE',''),
        'NAME': os.environ.get('NAME',''),
        'USER': os.environ.get('USER',''),
        'PASSWORD' : os.environ.get('PASSWORD',''),
        'HOST': os.environ.get('HOST',''),
        'PORT': os.environ.get('PORT',''),
    }
}
'''

# superbase cloud PostgreSQL Connection
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        # Use SSL locally and on Render (required by Supabase)
        ssl_require=True
    )
}

# Face Recognition Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 3600,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # test on your console instead
EMAIL_HOST = os.environ.get('EMAIL_HOST','')  # Or your email provider's SMTP host
EMAIL_PORT = os.environ.get('EMAIL_PORT','')  # Common port for TLS
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS','')  # Use TLS encryption
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER','')  # Your email address
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD','')  # An app-specific password if using Gmail/similar
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL','')  # Set a proper from email
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT','10'))  # Set email timeout in seconds

# Site Configuration for Email Links
SITE_URL = RENDER_EXTERNAL_HOSTNAME or 'http://localhost:8000'  # Change to your production domain in production
SITE_NAME = 'Church Membership and Attendance Management System'


# TWILIO SMS CONFIGURATION
# Get your credentials from https://www.twilio.com/console
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')  # Your Account SID
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')    # Your Auth Token
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '') # Your Twilio Phone Number (e.g., +1234567890)


# Actual directory user backups files go to
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#used on production with whitenoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "dbbackup": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            'location': os.path.join(os.path.dirname(BASE_DIR), 'uploads')
        },
     "staticfiles": {
        "BACKEND": 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
    },
}

'''
#used on Local Development only
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "dbbackup": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            'location': os.path.join(os.path.dirname(BASE_DIR), 'uploads')
        },
     "staticfiles": {
        "BACKEND": 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
    },
}
'''


DBBACKUP_FILENAME_TEMPLATE = 'backup_db_{datetime}.sql'
DBBACKUP_MEDIA_FILENAME_TEMPLATE = 'backup_file_{datetime}.tar'
#DBBACKUP_STORAGE_OPTIONS = {'location': os.path.join(os.path.dirname(BASE_DIR), 'uploads')}
#DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'uploads')

# URL used to access the media
MEDIA_URL = '/media/'

#custom user
AUTH_USER_MODEL = 'user.User'

#rest framework settings

REST_FRAMEWORK = {
'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
'PAGE_SIZE':10,
'MAX_PAGE_SIZE':10,
'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user':'1000/day',
        'refresh': '25/hour',
        'face_login': '100/day',
        'password_login': '100/day',
        'otp_login': '100/day',
        'password_reset_request':'100/day',
        'otp_verification':'100/day',
        'password_reset':'100/day',


    },
'DEFAULT_FILTER_BACKENDS': (
'django_filters.rest_framework.DjangoFilterBackend',
'rest_framework.filters.OrderingFilter',
'rest_framework.filters.SearchFilter',
),
'DEFAULT_AUTHENTICATION_CLASSES': (
'rest_framework_simplejwt.authentication.JWTAuthentication',
),
'DEFAULT_PERMISSION_CLASSES': (
            'rest_framework.permissions.IsAuthenticated', # Or other default permissions
),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
    'UPDATE_LAST_LOGIN': True,
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# different password hashers for better security(argon2 most secured and fastest, bcrypt is also secured and faster than default, pbkdf2 and pbkdf2sha1 are the default hashers and less secure and fast)
#to use any of the hashers make it come first in the list
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]
