# Generated by Django 4.2.16 on 2026-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_personid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_auth',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
