# Generated by Django 4.2.16 on 2026-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_two_factor_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
    ]
