# Generated by Django 4.2.16 on 2026-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_personid_alter_user_roleid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
    ]
