# Generated by Django 4.2.16 on 2026-04-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_alter_role_permissions'),
        ('person', '0006_alter_person_churchid'),
        ('user', '0006_alter_user_two_factor_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role'),
        ),
    ]
