# Generated by Django 5.2.8 on 2025-12-03 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('socialMedia', models.URLField(blank=True, null=True)),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('occupation', models.TextField(blank=True, null=True)),
                ('ethnicity', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], default='M')),
                ('marital_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('SEPARATED', 'SEPARATED')], default='MARRIED')),
                ('householdId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='household.household')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
            options={
                'ordering': ('marital_status', 'gender'),
            },
        ),
    ]
