# Generated by Django 5.2.8 on 2025-12-03 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('household', '0001_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('middleName', models.TextField()),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('entranceDate', models.DateTimeField()),
                ('faceEncoding', models.BinaryField(blank=True, null=True)),
                ('churchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
                ('householdId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='household.household')),
                ('membershipId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membership')),
            ],
            options={
                'ordering': ('firstName', 'lastName'),
            },
        ),
    ]
