# Generated by Django 4.2.16 on 2025-12-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faceEncoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
