# Generated by Django 4.2.16 on 2025-12-20 03:53

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        
    ]
