# Generated by Django 4.2.16 on 2025-12-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_faceencoding'),
        ('person', '0003_alter_person_faceencoding'),
    ]

    operations = [
    ]
