# Generated by Django 4.2.16 on 2026-01-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_merge_20251220_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='faceEncoding',
        ),
    ]
