# Generated by Django 5.2.8 on 2025-11-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
