# Generated by Django 4.2.16 on 2026-03-30 18:54

import church.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=church.models.upload_to),
        ),
    ]
