# Generated by Django 6.0.5 on 2026-05-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_church_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
