# Generated by Django 6.0.5 on 2026-05-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_church_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.CharField(default='welcome', max_length=500),
        ),
    ]
