# Generated by Django 5.2.8 on 2025-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('count', models.IntegerField()),
                ('head', models.TextField()),
                ('spouse', models.TextField()),
                ('children', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
