# Generated by Django 4.2.16 on 2025-12-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='children',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='spouse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
