# Generated by Django 4.2.16 on 2025-12-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_alter_household_children_alter_household_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
