# Generated by Django 5.2.8 on 2025-12-04 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('ministries', '0001_initial'),
        ('person', '0001_initial'),
        ('role', '0004_alter_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('churchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
                ('ministryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministries.ministries')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('roleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='role.role')),
            ],
        ),
    ]
