# Generated by Django 4.2.16 on 2026-03-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_church_logo'),
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='churchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.church'),
        ),
    ]
