# Generated by Django 5.2.8 on 2025-11-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('FACE', 'FACE'), ('FORM', 'FORM')], default='FORM', unique=True)),
                ('description', models.CharField(choices=[('Face Recognition', 'Face Recognition'), ('Manual Form Entry', 'Manual Form Entry')], default='Manual Form Entry', unique=True)),
            ],
            options={
                'ordering': ('method',),
            },
        ),
    ]
