# Generated by Django 4.2.16 on 2026-04-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturemethod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturemethod',
            name='description',
            field=models.CharField(choices=[('Face Attendance Capture', 'Face Attendance Capture'), ('Form Attendance Capture', 'Form Attendance Capture')], default='Form Attendance Capture', unique=True),
        ),
    ]
